import Nav from "@/components/Nav/Nav";
import "./globals.css";
import Footer from "@/components/Footer/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-google text-white">
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
